{{- if .Values.dockercfg}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-dockercfg
  annotations:
    harness.io/skip-versioning: "true"
data:
  .dockercfg: {{.Values.dockercfg}}
type: kubernetes.io/dockercfg
---
{{- end}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        app.kubernetes.io/version: {{.Values.version}}
    spec:  
      containers:
      - args: ["sh", "-c", 'export SERVICE_NAME="${NAMESPACE_NAME}-FoodTruck" && export OTEL_RESOURCE_ATTRIBUTES="service.name=$SERVICE_NAME,deployment.environment=dev" && python3 app.py']
        env:
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://grafana-k8s-monitoring-alloy-receiver.grafana-cloud.svc.cluster.local:4317
        image: {{.Values.image}}
        imagePullPolicy: Always
        name: foodtruck
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
      restartPolicy: Always
      imagePullSecrets:
      - name: {{.Values.name}}-dockercfg


---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - name: web
    port: 5000
    targetPort: 5000
  selector:
    app: web
  type: LoadBalancer
